# Generated by Django 3.0.8 on 2020-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='picture',
            field=models.CharField(default='https://place-hold.it/100x60', max_length=20),
        ),
    ]
