# Generated by Django 3.0.8 on 2020-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_specialty_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default='https://place-hold.it/100x60', max_length=20),
        ),
    ]
