# Generated by Django 3.0.8 on 2020-08-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200801_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='compania',
            field=models.CharField(default='', max_length=15),
        ),
    ]
